### ISSUE TITLE
Change name to mercateo-spring-boot-starter-hornetq-cluster

### ISSUE THREAD

**Issue by philipp-classen** [Mercateo/mercateo-spring-boot-starter-hornetq-cluster#2]
I would recommend to change the name because spring-boot-starter-\* is reserved for official starters. Instead mercateo-spring-boot-starter-hornetq-cluster would be their proposal:
- http://docs.spring.io/spring-boot/docs/1.4.0.RC1/reference/htmlsingle/#using-boot-starter
- http://docs.spring.io/spring-boot/docs/1.4.0.RC1/reference/htmlsingle/#boot-features-custom-starter-naming

**Comment by leflamm** [comment]
Can't argue with that I guess. Going to rename it. Thanks!

**Comment by leflamm** [comment]
repo, project, URLs, packages renamed
